export const INIT_DATA = "INIT_DATA";
export const SET_TOKEN = "SET_TOKEN";
export const SET_INITIALIZED = "SET_INITIALIZED";
export const SET_ORGANIZATION = "SET_ORGANIZATION";
export const SET_ORGANIZATIONS = "SET_ORGANIZATIONS";
export const SET_ALLOWED_ACTION = "SET_ALLOWED_ACTION";
